package ravtrix.backpackerbuddy.recyclerviewfeed.travelpostsrecyclerview;

import java.util.HashMap;

import ravtrix.backpackerbuddy.R;

/**
 * Created by Ravinder on 4/5/16.
 */
public class BackgroundImage {
    private HashMap<String, Integer> backGroundHashMap;

    public BackgroundImage () {
        backGroundHashMap = new HashMap<>();
        setBackgroundHashMap();
    }

    private void setBackgroundHashMap() {
        backGroundHashMap.put("Afghanistan", R.drawable.asia);
        backGroundHashMap.put("Albania", R.drawable.europe);
        backGroundHashMap.put("Algeria", R.drawable.africa);
        backGroundHashMap.put("Andorra", R.drawable.europe);
        backGroundHashMap.put("Angola", R.drawable.africa);
        backGroundHashMap.put("Antigua and Barbuda", R.drawable.america);
        backGroundHashMap.put("Argentina", R.drawable.america);
        backGroundHashMap.put("Armenia", R.drawable.asia);
        backGroundHashMap.put("Aruba", R.drawable.america);
        backGroundHashMap.put("Australia", R.drawable.australia);
        backGroundHashMap.put("Austria", R.drawable.europe);
        backGroundHashMap.put("Azerbaijan", R.drawable.asia);
        backGroundHashMap.put("Bahamas", R.drawable.america);
        backGroundHashMap.put("Bahrain", R.drawable.asia);
        backGroundHashMap.put("Bangladesh", R.drawable.asia);
        backGroundHashMap.put("Barbados", R.drawable.america);
        backGroundHashMap.put("Belarus", R.drawable.europe);
        backGroundHashMap.put("Belgium", R.drawable.europe);
        backGroundHashMap.put("Belize", R.drawable.america);
        backGroundHashMap.put("Benin", R.drawable.africa);
        backGroundHashMap.put("Bhutan", R.drawable.asia);
        backGroundHashMap.put("Bolivia", R.drawable.america);
        backGroundHashMap.put("Bosnia and Herzegovina", R.drawable.europe);
        backGroundHashMap.put("Botswana", R.drawable.africa);
        backGroundHashMap.put("Brazil", R.drawable.america);
        backGroundHashMap.put("British Virgin Islands", R.drawable.america);
        backGroundHashMap.put("Brunei", R.drawable.asia);
        backGroundHashMap.put("Bulgaria", R.drawable.europe);
        backGroundHashMap.put("Burundi", R.drawable.africa);
        backGroundHashMap.put("Cambodia", R.drawable.asia);
        backGroundHashMap.put("Cameroon", R.drawable.africa);
        backGroundHashMap.put("Canada", R.drawable.america);
        backGroundHashMap.put("Cape Verde", R.drawable.africa);
        backGroundHashMap.put("Cayman Islands", R.drawable.america);
        backGroundHashMap.put("Chad", R.drawable.africa);
        backGroundHashMap.put("Chile", R.drawable.america);
        backGroundHashMap.put("China", R.drawable.asia);
        backGroundHashMap.put("Colombia", R.drawable.america);
        backGroundHashMap.put("Comoros", R.drawable.africa);
        backGroundHashMap.put("Congo", R.drawable.africa);
        backGroundHashMap.put("Costa Rica", R.drawable.america);
        backGroundHashMap.put("Croatia", R.drawable.europe);
        backGroundHashMap.put("Cuba", R.drawable.america);
        backGroundHashMap.put("Curacao", R.drawable.america);
        backGroundHashMap.put("Cyprus", R.drawable.asia);
        backGroundHashMap.put("Czech Republic", R.drawable.europe);
        backGroundHashMap.put("Denmark", R.drawable.europe);
        backGroundHashMap.put("Djibouti", R.drawable.africa);
        backGroundHashMap.put("Dominica", R.drawable.america);
        backGroundHashMap.put("Dominican Republic", R.drawable.america);
        backGroundHashMap.put("Ecuador", R.drawable.america);
        backGroundHashMap.put("Egypt", R.drawable.africa);
        backGroundHashMap.put("El Salvador", R.drawable.america);
        backGroundHashMap.put("Equatorial Guinea", R.drawable.africa);
        backGroundHashMap.put("Eritrea", R.drawable.africa);
        backGroundHashMap.put("Estonia", R.drawable.europe);
        backGroundHashMap.put("Ethiopia", R.drawable.africa);
        backGroundHashMap.put("Fiji", R.drawable.oceania);
        backGroundHashMap.put("Finland", R.drawable.europe);
        backGroundHashMap.put("France", R.drawable.europe);
        backGroundHashMap.put("Gabon", R.drawable.africa);
        backGroundHashMap.put("Gambia", R.drawable.africa);
        backGroundHashMap.put("Georgia", R.drawable.europe);
        backGroundHashMap.put("Germany", R.drawable.europe);
        backGroundHashMap.put("Ghana", R.drawable.africa);
        backGroundHashMap.put("Greece", R.drawable.europe);
        backGroundHashMap.put("Greenland", R.drawable.america);
        backGroundHashMap.put("Grenada", R.drawable.america);
        backGroundHashMap.put("Guadeloupe", R.drawable.america);
        backGroundHashMap.put("Guam", R.drawable.oceania);
        backGroundHashMap.put("Guatemala", R.drawable.america);
        backGroundHashMap.put("Guinea", R.drawable.africa);
        backGroundHashMap.put("Guyana", R.drawable.africa);
        backGroundHashMap.put("Haiti", R.drawable.america);
        backGroundHashMap.put("Honduras", R.drawable.america);
        backGroundHashMap.put("Hong Kong", R.drawable.asia);
        backGroundHashMap.put("Hungary", R.drawable.europe);
        backGroundHashMap.put("Iceland", R.drawable.europe);
        backGroundHashMap.put("India", R.drawable.asia);
        backGroundHashMap.put("Indonesia", R.drawable.asia);
        backGroundHashMap.put("Iran", R.drawable.asia);
        backGroundHashMap.put("Iraq", R.drawable.asia);
        backGroundHashMap.put("Ireland", R.drawable.europe);
        backGroundHashMap.put("Israel", R.drawable.asia);
        backGroundHashMap.put("Italy", R.drawable.europe);
        backGroundHashMap.put("Ivory Coast", R.drawable.africa);
        backGroundHashMap.put("Jamaica", R.drawable.america);
        backGroundHashMap.put("Japan", R.drawable.asia);
        backGroundHashMap.put("Jordan", R.drawable.asia);
        backGroundHashMap.put("Kazakhstan", R.drawable.asia);
        backGroundHashMap.put("Kenya", R.drawable.africa);
        backGroundHashMap.put("Kiribati", R.drawable.oceania);
        backGroundHashMap.put("Kuwait", R.drawable.asia);
        backGroundHashMap.put("Kosovo", R.drawable.europe);
        backGroundHashMap.put("Kyrgyzstan", R.drawable.asia);
        backGroundHashMap.put("Laos", R.drawable.asia);
        backGroundHashMap.put("Latvia", R.drawable.europe);
        backGroundHashMap.put("Lebanon", R.drawable.asia);
        backGroundHashMap.put("Lesotho", R.drawable.africa);
        backGroundHashMap.put("Liberia", R.drawable.africa);
        backGroundHashMap.put("Libya", R.drawable.africa);
        backGroundHashMap.put("Liechtenstein", R.drawable.europe);
        backGroundHashMap.put("Lithuania", R.drawable.europe);
        backGroundHashMap.put("Luxembourg", R.drawable.europe);
        backGroundHashMap.put("Macau", R.drawable.asia);
        backGroundHashMap.put("Macedonia", R.drawable.europe);
        backGroundHashMap.put("Madagascar", R.drawable.africa);
        backGroundHashMap.put("Malawi", R.drawable.africa);
        backGroundHashMap.put("Malaysia", R.drawable.asia);
        backGroundHashMap.put("Maldives", R.drawable.asia);
        backGroundHashMap.put("Mali", R.drawable.africa);
        backGroundHashMap.put("Malta", R.drawable.europe);
        backGroundHashMap.put("Martinique", R.drawable.america);
        backGroundHashMap.put("Mauritania", R.drawable.africa);
        backGroundHashMap.put("Mauritius", R.drawable.africa);
        backGroundHashMap.put("Mexico", R.drawable.america);
        backGroundHashMap.put("Moldova", R.drawable.europe);
        backGroundHashMap.put("Monaco", R.drawable.europe);
        backGroundHashMap.put("Mongolia", R.drawable.asia);
        backGroundHashMap.put("Montenegro", R.drawable.europe);
        backGroundHashMap.put("Morocco", R.drawable.africa);
        backGroundHashMap.put("Mozambique", R.drawable.africa);
        backGroundHashMap.put("Myanmar", R.drawable.asia);
        backGroundHashMap.put("Namibia", R.drawable.africa);
        backGroundHashMap.put("Nauru", R.drawable.oceania);
        backGroundHashMap.put("Nepal", R.drawable.asia);
        backGroundHashMap.put("Netherlands", R.drawable.europe);
        backGroundHashMap.put("New Zealand", R.drawable.oceania);
        backGroundHashMap.put("Nicaragua", R.drawable.america);
        backGroundHashMap.put("Niger", R.drawable.africa);
        backGroundHashMap.put("Nigeria", R.drawable.africa);
        backGroundHashMap.put("North Korea", R.drawable.asia);
        backGroundHashMap.put("Norway", R.drawable.europe);
        backGroundHashMap.put("Oman", R.drawable.asia);
        backGroundHashMap.put("Pakistan", R.drawable.asia);
        backGroundHashMap.put("Panama", R.drawable.america);
        backGroundHashMap.put("Papua New Guinea", R.drawable.oceania);
        backGroundHashMap.put("Paraguay", R.drawable.america);
        backGroundHashMap.put("Peru", R.drawable.america);
        backGroundHashMap.put("Philippines", R.drawable.asia);
        backGroundHashMap.put("Poland", R.drawable.europe);
        backGroundHashMap.put("Portugal", R.drawable.europe);
        backGroundHashMap.put("Puerto Rico", R.drawable.america);
        backGroundHashMap.put("Qatar", R.drawable.asia);
        backGroundHashMap.put("Romania", R.drawable.europe);
        backGroundHashMap.put("Russia", R.drawable.europe);
        backGroundHashMap.put("Rwanda", R.drawable.africa);
        backGroundHashMap.put("Saint Lucia", R.drawable.america);
        backGroundHashMap.put("Samoa", R.drawable.oceania);
        backGroundHashMap.put("Saudi Arabia", R.drawable.asia);
        backGroundHashMap.put("Senegal", R.drawable.africa);
        backGroundHashMap.put("Serbia", R.drawable.europe);
        backGroundHashMap.put("Sierra Leone", R.drawable.africa);
        backGroundHashMap.put("Singapore", R.drawable.asia);
        backGroundHashMap.put("Slovakia", R.drawable.europe);
        backGroundHashMap.put("Slovenia", R.drawable.europe);
        backGroundHashMap.put("Solomon Islands", R.drawable.oceania);
        backGroundHashMap.put("Somalia", R.drawable.africa);
        backGroundHashMap.put("South Africa", R.drawable.africa);
        backGroundHashMap.put("South Korea", R.drawable.asia);
        backGroundHashMap.put("Spain", R.drawable.europe);
        backGroundHashMap.put("Sri Lanka", R.drawable.asia);
        backGroundHashMap.put("Sudan", R.drawable.africa);
        backGroundHashMap.put("Suriname", R.drawable.america);
        backGroundHashMap.put("Swaziland", R.drawable.africa);
        backGroundHashMap.put("Sweden", R.drawable.europe);
        backGroundHashMap.put("Switzerland", R.drawable.europe);
        backGroundHashMap.put("Syria", R.drawable.asia);
        backGroundHashMap.put("Taiwan", R.drawable.asia);
        backGroundHashMap.put("Tajikistan", R.drawable.asia);
        backGroundHashMap.put("Tanzania", R.drawable.africa);
        backGroundHashMap.put("Thailand", R.drawable.asia);
        backGroundHashMap.put("Togo", R.drawable.africa);
        backGroundHashMap.put("Tonga", R.drawable.oceania);
        backGroundHashMap.put("Trinidad and Tobago", R.drawable.america);
        backGroundHashMap.put("Tunisia", R.drawable.africa);
        backGroundHashMap.put("Turkey", R.drawable.asia);
        backGroundHashMap.put("Turks and Caicos", R.drawable.america);
        backGroundHashMap.put("Tuvalu", R.drawable.oceania);
        backGroundHashMap.put("Uganda", R.drawable.africa);
        backGroundHashMap.put("Ukraine", R.drawable.europe);
        backGroundHashMap.put("United Arab Emirates", R.drawable.asia);
        backGroundHashMap.put("United Kingdom", R.drawable.europe);
        backGroundHashMap.put("United States", R.drawable.america);
        backGroundHashMap.put("U.S. Virgin Islands", R.drawable.america);
        backGroundHashMap.put("Uruguay", R.drawable.america);
        backGroundHashMap.put("Uzbekistan", R.drawable.asia);
        backGroundHashMap.put("Vanuatu", R.drawable.oceania);
        backGroundHashMap.put("Venezuela", R.drawable.america);
        backGroundHashMap.put("Vietnam", R.drawable.asia);
        backGroundHashMap.put("Yemen", R.drawable.asia);
        backGroundHashMap.put("Zambia", R.drawable.africa);
        backGroundHashMap.put("Zimbabwe", R.drawable.africa);
    }

    public int getBackgroundFromHash(String countryName) {
        return backGroundHashMap.get(countryName);
    }
}